name: Deploy Suetolog Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Вход на сервер по SSH и деплой
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            # Переходим в директорию с проектом
            cd /root/suetolog-bot
            # Обновляем репозиторий
            git pull origin master
            # Останавливаем и удаляем контейнер с именем suetolog-bot, если он существует
            docker rm -f suetolog-bot || true
            # Собираем новый образ
            docker build -t suetolog-bot .
            docker run -d --name suetolog-bot --env-file .env -v suetolog-bot:/app/bot suetolog-bot
